version: '3.8'
services: 
 prometheus:
  image: prom/prometheus:v2.44.0
  container_name: prometheus
  ports:
   - "9090:9090"
  networks:
   - prom_net
  volumes:
   - ./config/prometheus:/etc/prometheus
   
 mysql:
  image: mysql:8.0
  container_name: mysql
  ports:
   - "3306:3306"
  networks:
   - prom_net
  environment:
   MYSQL_DATABASE: dbtest
   MYSQL_ROOT_PASSWORD: iol2023
   MYSQL_USER: invertir
   MYSQL_PASSWORD: online
  
 mysql_exporter:
  image: prom/mysqld-exporter:v0.14.0
  container_name: mysql_exporter
  ports:
   - "9104:9104"
  networks:
   - prom_net
  environment:
   DATA_SOURCE_NAME: root:iol2023@(mysql:3306)/dbtest
    
 alertmanager:
  image: prom/alertmanager:v0.24.0
  container_name: alert_manager
  ports: 
   - "9093:9093"
  networks:
   - prom_net
  volumes:
   - ./config/alertmanager:/etc/alertmanager/
   
 node_exporter:
  image: prom/node-exporter:v1.0.1
  container_name: node_exporter
  ports: 
   - "9100:9100"
  networks:
   - prom_net
  
 grafana:
  image: grafana/grafana:7.5.1 
  container_name: grafana  
  ports: 
   - "3000:3000"
  networks:
   - prom_net
  user: '0'
  volumes:
   - ./config/grafana:/var/lib/grafana/
  
networks:
 prom_net:
  driver: bridge
