global:
  # e onde eu agrupo as alertas para disparar todas juntas
  #group_interval: 15s

route:
 receiver: Default
 group_interval: 15s
 repeat_interval: 1m
 group_by: 
  - alertname
 group_wait: 15s

 routes: 
  - receiver: email_notifications
    match: 
     team: mysqlAndDocker

  - receiver: email_notifications
    match: 
     team: node

receivers: 
- name: Default
  webhook_configs: 
  - url: 'https://pruu.herokuapp.com/dump/wpwebhookdefault'

- name: email_notifications
  email_configs:
  - to: emailtest1
    from: emailtest2
    smarthost: smtp.gmail.com:587
    auth_username: emailtest1
    auth_identity: emailtest1
    auth_password: your-password
    send_resolved: true
