global:
  # e onde eu agrupo as alertas para disparar todas juntas
  #group_interval: 15s

route:
 receiver: Default
 group_interval: 15s
 repeat_interval: 1m
 group_by: 
  - alertname
 group_wait: 15s

 routes: 
  - receiver: email_notifications
    match: 
     team: mysqlAndDocker

  - receiver: email_notifications
    match: 
     team: node

receivers: 
- name: Default
  webhook_configs: 
  - url: 'https://pruu.herokuapp.com/dump/wpwebhookdefault'

- name: email_notifications
  email_configs:
  - to: emailtest1
    from: emailtest2
    smarthost: smtp.gmail.com:587
    auth_username: emailtest1
    auth_identity: emailtest1
    auth_password: your-password
    send_resolved: true
    
    
   ####################################### ANOTHER EXAMPLE SET UP ALERTMANAGER,ONLY WITH SLACK ##########################################
receivers: 
- name: slack_notification
  slack_configs:
  - channel: '#CHANNEL-TEST'
    api_url: 'SLACK_URL
    send_resolved: true
    icon_url: https://avatars3.githubusercontent.com/u/3380462
    title: |-
        [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
        {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
          {{" "}}(
          {{- with .CommonLabels.Remove .GroupLabels.Names }}
            {{- range $index, $label := .SortedPairs -}}
              {{ if $index }}, {{ end }}
              {{- $label.Name }}="{{ $label.Value -}}"
            {{- end }}
          {{- end -}}
          )
        {{- end }}
    text: >-
        {{ range .Alerts -}}
        *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}
        *Description:* {{ .Annotations.description }}
        *Details:*
          {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
          {{ end }}
        {{ end }}

route:
 receiver: slack_notification
 group_interval: 15s
 repeat_interval: 1m
 group_by: 
  - alertname
 group_wait: 15s
    
