groups:
- name: mysqlAndDocker
  rules:
  - alert: MySQLdown
    expr: mysql_up == 0
    for: 30s
    labels:
     team: mysqlAndDocker
     severity: "critical"
    annotations:
     titulo: "{{ $labels.instance }} down"
     descricao: "{{ $labels.instance}} of job {{ $labels.job }} has been down for more than 30 segundos. "

  - alert: dockerDown
    expr: count(container_last_seen{instance=~"172\\.17\\.0\\.4:8080",image=~"(.)+"}) < 6.9
    for: 30s
    labels:
     team: mysqlAndDocker
     severity: "high"
    annotations:
     titulo: "caiu container"
     descricao: "caiu algum dos container que estavam levantado!"

- name: groupNode
  rules:
  - alert: InstanceNodeStopped
    expr: up{instance="172.17.0.8:9100", job="node_exporter"} == 0
    for: 30s
    labels:
     time: node
     severity: "high"
    annotations:
     titulo: "caiu NODE"
     descricao: "caiu o NODE, RAPIDOOOO SOLUCIONEEEEE!!!"