ggroups:
- name: mysqlAndDocker.alerts
  rules:
  - alert: MySQLdown
    expr: mysql_up == 0
    for: 30s
    labels:
     team: mysqlAndDocker
     severity: "high"
    annotations:
     description : '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 30 segundos. '
     title: mysqlAndDocker


  - alert: dockerDown
    expr: count(container_last_seen{instance=~"IP_CADVISOR_CONTAINER",image=~"(.)+"}) < 6.9
    for: 30s
    labels:
     team: mysqlAndDocker
     severity: "high"
    annotations:
     title: "caiu algum container de API da {{ $labels.instance }}"
     description : "{{ $labels.instance }} caiu algum dos container que estavam levantado! faz 30 segundos,rever!"

- name: groupInstance.alerts
  rules:
  - alert: InstanceStopped
    expr: up == 0
    for: 30s
    labels:
     team: server
     severity: "critical"
    annotations:
     title: "caiu {{ $labels.instance }}"
     description : "caiu a siguiente IP {{ $labels.instance }}, do job {{ $labels.job }} RAPIDOOOO SOLUCIONEEEEE!!!"
