global:
 scrape_interval: 15s
 evaluation_interval: 15s

alerting:
 alertmanagers:
 - static_configs:
   - targets:
     - IP_ALERT_MANAGER_CONTAINER:9093

rule_files:
 - alerts.rules.yml

scrape_configs:
 - job_name: prometheus
   static_configs:
   - targets:
     - localhost:9090
 
 - job_name: cadvisor
   static_configs:
   - targets:
     - IP_CADVISOR_CONTAINER:8080
     labels:
       group: 'cadvisor_webvm3'

 - job_name: mysql_exporter
   static_configs:
   - targets:
     - IP_MYSQL_CONTAINER:9104
     labels:
       group: 'mysql_webvm3'
 
 - job_name: node_exporter
   static_configs:
   - targets:
     - IP_NODE_CONTAINER:9100
     labels:
       group: 'node_exporter_webvm3'
