global:
 scrape_interval: 15s
 evaluation_interval: 15s

alerting:
 alertmanagers:
 - static_configs:
   - targets:
     - 172.17.0.2:9093

rule_files:
 - alerts.rules.yml

scrape_configs:
 - job_name: prometheus
   static_configs:
   - targets:
     - localhost:9090
 
 - job_name: cadvisor
   static_configs:
   - targets:
     - 172.17.0.4:8080

 - job_name: mysql_exporter
   static_configs:
   - targets:
     - 172.17.0.3:9104
 
 - job_name: node_exporter
   static_configs:
   - targets:
     - 172.17.0.8:9100